### ISSUE TITLE
FileNotFoundError while installing ecos==2.0.11

### ISSUE THREAD

**Issue by sujeendran** [embotech/ecos-python#46]
Hi,
Our team uses cvxpy package for Airflow recipes and we came across some errors happening during the recipe build process pip installation of the latest ecos package:
```bash
Collecting ecos>=2 (from cvxpy==1.0.21->-r /python_requirements/requirements_spark3_7.txt (line 3))
Downloading https://files.pythonhosted.org/packages/84/2a/1480b85692f349fd669655e020a1aafdd2b798eab69305d394989f1d2b64/ecos-2.0.11.tar.gz (141kB)
Installing build dependencies: started
Installing build dependencies: finished with status 'done'
Getting requirements to build wheel: started
Getting requirements to build wheel: finished with status 'error'
Complete output from command /opt/pyenv/versions/3.7.4/bin/python3.7 /opt/pyenv/versions/3.7.4/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpwfkf809e:
Traceback (most recent call last):
  File "/opt/pyenv/versions/3.7.4/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
    main()
  File "/opt/pyenv/versions/3.7.4/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/opt/pyenv/versions/3.7.4/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 54, in get_requires_for_build_wheel
    return hook(config_settings)
  File "/tmp/pip-build-env-souez5we/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=['wheel'])
  File "/tmp/pip-build-env-souez5we/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
    self.run_setup()
  File "/tmp/pip-build-env-souez5we/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 485, in run_setup
    self).run_setup(setup_script=setup_script)
  File "/tmp/pip-build-env-souez5we/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 335, in run_setup
    exec(code, locals())
  File "<string>", line 70, in <module>
FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
```

Fixing the version in our requirements.txt to `ecos==2.0.10` seems to be workaround for now.

**Comment by andruten** [comment]
Same here @sujeendran. Are you using ARM architecture?

**Comment by phschiele** [comment]
Version `2.0.12` should fix the issue: https://pypi.org/project/ecos/2.0.12/#files
Thanks @andruten for the fix!

**Comment by sujeendran** [comment]
> Same here @sujeendran. Are you using ARM architecture?

No, we were using x86-64. Thanks for pushing the fix!
